export const caseTypeLabels: Record<string, string> = {
  pension_review: "Pension Review",
  retirement_planning: "Retirement Planning",
  salary_exchange: "Salary Exchange",
  transfer_advice: "Transfer Advice",
  survivor_protection: "Survivor Protection",
  decumulation: "Decumulation",
  other: "Other",
}

export const statusStyles: Record<string, string> = {
  draft: "bg-slate-100 text-slate-600",
  in_preparation: "bg-blue-50 text-blue-700 border border-blue-200",
  ready_for_review: "bg-amber-50 text-amber-700 border border-amber-200",
  in_review: "bg-purple-50 text-purple-700 border border-purple-200",
  approved: "bg-emerald-50 text-emerald-700 border border-emerald-200",
  completed: "bg-green-50 text-green-800 border border-green-200",
  archived: "bg-slate-50 text-slate-400",
}

export const statusLabels: Record<string, string> = {
  draft: "Draft",
  in_preparation: "In Preparation",
  ready_for_review: "Ready for Review",
  in_review: "In Review",
  approved: "Approved",
  completed: "Completed",
  archived: "Archived",
}

export const categoryStyles: Record<string, string> = {
  product_rule: "bg-blue-50 text-blue-700",
  internal_policy: "bg-violet-50 text-violet-700",
  regulatory_requirement: "bg-amber-50 text-amber-700",
  playbook: "bg-emerald-50 text-emerald-700",
  precedent: "bg-slate-100 text-slate-600",
  faq: "bg-sky-50 text-sky-700",
  process_guide: "bg-rose-50 text-rose-700",
}

export const categoryLabels: Record<string, string> = {
  product_rule: "Product Rule",
  internal_policy: "Internal Policy",
  regulatory_requirement: "Regulatory",
  playbook: "Playbook",
  precedent: "Precedent",
  faq: "FAQ",
  process_guide: "Process Guide",
}

export const sourceTypeStyles: Record<string, string> = {
  product_rule: "bg-blue-50 text-blue-700",
  internal_policy: "bg-violet-50 text-violet-700",
  regulation: "bg-amber-50 text-amber-700",
  market_data: "bg-emerald-50 text-emerald-700",
  client_data: "bg-sky-50 text-sky-700",
  precedent: "bg-slate-100 text-slate-600",
  expert_knowledge: "bg-rose-50 text-rose-700",
}

export const auditActionLabels: Record<string, string> = {
  case_created: "Case created",
  case_assigned: "Case assigned",
  recommendation_generated: "Recommendation generated by AI",
  recommendation_edited: "Recommendation edited",
  recommendation_reviewed: "Recommendation reviewed",
  recommendation_approved: "Recommendation approved",
  recommendation_rejected: "Recommendation rejected",
  document_generated: "Document generated",
  compliance_check_passed: "Compliance check passed",
  compliance_check_failed: "Compliance check failed",
  case_completed: "Case completed",
  knowledge_referenced: "Knowledge referenced",
  workflow_step_completed: "Workflow step completed",
  workflow_paused: "Workflow paused",
  workflow_resumed: "Workflow resumed",
  meeting_brief_generated: "Meeting brief generated by AI",
  document_ingested: "Document ingested by AI",
  client_data_applied: "Client data updated from document",
  knowledge_ingested: "Knowledge document ingested",
}
